### ISSUE TITLE
help! 

### ISSUE THREAD

**Issue by WISH12345** [the-cult-of-integral/discord-raidkit#33]
██████╗ ███████╗████████╗███████╗███████╗██╗  ██╗
                                     ██╔═══██╗██╔════╝╚══██╔══╝██╔════╝██╔════╝██║  ██║
                                     ██║   ██║█████╗     ██║   █████╗  ███████╗███████║
                                     ██║▄▄ ██║██╔══╝     ██║   █Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021152FC74C0>
Traceback (most recent call last):
  File "C:\Users\-\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\-\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\-\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()

**Comment by linus-jansson** [comment]
I think you cut out part of the error message?

**Comment by the-cult-of-integral** [comment]
Not enough info provided - invalid
