### ISSUE TITLE
Error after choosing bot

### ISSUE THREAD

**Issue by lITronusIl** [the-cult-of-integral/discord-raidkit#67]
ill have the following problem after selecting a bot: Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Tristan\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Tristan\Downloads\discord-raidkit-master\Discord Raidkit v2.3.4\tools\raider.py", line 76, in on_ready
    await self.tree.sync()
          ^^^^^^^^^
AttributeError: 'Raider' object has no attribute 'tree'

**Comment by AsuxAX** [comment]
That means that the Raider object (which I assume is the Discord Bot you chose) does not have a attribute named tree.
It might be that the Raider class didn't inherit correctly from the discord.Bot class.
